### ISSUE TITLE
Inconsistent parsing for wit/datetime

### ISSUE THREAD

**Issue by sumitbinnani** [wit-ai/duckling#100]
When using wit/datetime as entity:

``Terminate at 10 am`` is parsed as:
```
5/7/2016, 10:00:00 AM
```

However, ``Terminate at 12 am`` is parsed as:
```
from 5/8/2016, 12:00:00 AM to 5/8/2016, 12:00:00 PM
```

**Comment by l5t** [comment]
Should be fixed.
