### ISSUE TITLE
Reference time

### ISSUE THREAD

**Issue by cromulus** [wit-ai/duckling#106]
Similar to the wit.ai interface, the context object allows you to set a reference time, from which all datetimes are evaluated. 

This allows an app to set the reference time to next friday, and then when the user says "1pm" we can know that 1pm refers to 1pm next friday.

Any way to do that with duckling directly?

Thanks!

**Comment by l5t** [comment]
Something like this: 
```(play :en$core "today" nil {:reference-time (time/t -2 2016 5 24 4 30)})```
