### ISSUE TITLE
Contribute [Add new language][Indonesian]

### ISSUE THREAD

**Issue by opam22** [wit-ai/duckling#116]
Hi folks,

I wanna contribute to add new language, which is indonesian, how can I do that?

Looking forward hearing back from you.

**Comment by l5t** [comment]
Thanks a lot. Here is how to extend Duckling to new domains and/or new languages. If the tests don't pass, prepend the corpus/rules files with an underscore (_). This allows to save your work while getting help from somebody else when needed.

**How to add a new language?**

To add support for a new language, follow these steps:

- Run the script bin/add-new-language.sh

- Create at least one corpus file in resources/languages/<lang>/corpus (you might duplicate an existing file to get started).

- Create at least one rules file in resources/languages/<lang>/rules.

- Reload(see https://duckling.wit.ai/)

- Run your module corpus, add tests, see them fail, add rules until everything passes.

**Comment by opam22** [comment]
If it's not my mistaken, I have to clone this repo first, add new language (based on your instruction) and make pull request, right?

**Comment by l5t** [comment]
exactly

**Comment by opam22** [comment]
Great! will do it ASAP
