### ISSUE TITLE
(p/load!) failing with Duckling 0.4.0+

### ISSUE THREAD

**Issue by gnardari** [wit-ai/duckling#117]
I tried to update Duckling on project and the exact same code works on "0.3.9" but on "0.4.0"+ I get 

`java.lang.IllegalStateException: Can't set!: null from non-binding thread` when calling ` (p/load!)`

Even the simple ReadMe example is failing. I'm very new to Clojure so it might be something on my end but thought someone here could help.

**Comment by vstabile** [comment]
This seems to happen when packaging up the project into a jar file. Does anyone know how to make it work?

**Comment by ar7hur** [comment]
We had an issue in commit 25ee94df210cda5e23aab4ecb4021b85ab3c9dfb, I just reverted it while the contributor takes a look at it. It should be OK now. Sorry for the inconvenience.

**Comment by savvopoulos** [comment]
for what it's worth, I can still reproduce this issue with 0.4.18;

simply having `(p/load! {:languages ["en"]})` in the *global* scope, gives me the same error when running `lein uberjar`

**Comment by dvdnglnd** [comment]
Just as another data point, I am seeing this using 4.2.24.

My quick workaround was to wrap in a [`delay`](https://clojuredocs.org/clojure.core/delay).

Would be happy to help fix this. Any ideas on where to start?
