### ISSUE TITLE
Why Thai language is missing now.

### ISSUE THREAD

**Issue by golfapipol** [wit-ai/duckling#136]

**Comment by golfapipol** [comment]
Sorry, I misunderstand in duckling don't have Thai language yet
but in Wit.ai of thai language 
- Wit/amount_of_money
- Wit/number
is missing now

**Comment by icalF** [comment]
Same happened with Indonesian. I have to migrate to Wit/age_of_person to detect numerical value

**Comment by patapizza** [comment]
Hi,

We removed the Wit builtin entities relying on Duckling that don't have proper language support in Duckling (they wouldn't work).
As soon as these entities have the required language support in Duckling, they'll also be available in Wit.

Julien
