### ISSUE TITLE
[Italian] "san silvestro" and "notte di san silvestro" examples are failing

### ISSUE THREAD

**Issue by patapizza** [wit-ai/duckling#210]
```
duckling.core=> (load!)
duckling.core=> (run)
...
:it$core: 534 examples, 2 failed.
...
```

cc @ibobo - can you take a look at this?

**Comment by ibobo** [comment]
I have no failing examples... checked on my repository with the latest master merged and also on a fresh clone of the main repository

**Comment by ibobo** [comment]
I found that two rules did the same thing (I restructured that part last night), maybe that's causing the problem on your part. Still I don't understand how my repo can work if your's failing... anyway, will send a new pull request in a few minutes.

**Comment by ibobo** [comment]
Sorry... no luck... the `<time> notte` and `<time> notte` rules need to stay there. Hope you find the culprit.

**Comment by patapizza** [comment]
Thanks for checking @ibobo.
I still have the issue using a fresh copy of the repo. Might be just my environment.

Someone else can confirm?

**Comment by l5t** [comment]
Works for me. 
![image](https://cloud.githubusercontent.com/assets/6992759/22393357/b1aff9dc-e4b9-11e6-9356-993c98c6f886.png)
Please reopen if not working for you

**Comment by bisoldi** [comment]
I'm actually getting this failure (see below) using the maven dependency v. 0.4.23.

"not found" "san silvestro"
"not found" "notte di san silvestro"

I'm doing this while trying to call Duckling via Java.  I am experiencing other issues as well, which i'll open another ticket for, but wanted to add to this ticket.

**Comment by FraBle** [comment]
@bisoldi: any update on this?

**Comment by bisoldi** [comment]
@FraBle No update.  We implemented Duckling and got it to run, though this issue still existed.  I don't think it was a fatal error, so we just left it.
