### ISSUE TITLE
Efforts required adding rules for new language

### ISSUE THREAD

**Issue by ajay978** [wit-ai/duckling#217]
In our project we are planning to use Duckling.  Currently Duckling doesn't have "time" entity support in Japanese. Can someone comment how much  effort will be required for beginner to have it ?  Also is there any good tutorial to understand duckling rules and corpus ?
cc: @l5t

**Comment by patapizza** [comment]
Hi @ajay978,
Sorry for the late reply.
You can find comprehensive documentation on rules/corpus at https://duckling.wit.ai (under "Extending Duckling"). Usually the best way would be to copy the existing rules files of a close language and update/remove the rules.
