### ISSUE TITLE
Documentation: joining multiple tokens without whitespace

### ISSUE THREAD

**Issue by Mikulas** [wit-ai/duckling#231]
Hi, I'm extending duckling with support for Czech. I've run into an issue where I need to join multiple tokens without a space. The closest analog in English would be `three and thirty`, but we write it as `třiatřicet`.

If spaces were allowed, the rule would look like this:
```closure
  "digit prefixed tens"
  [(integer 1 9) (integer 10 90 #(#{20 30 40 50 60 70 80 90} (:value %)))]
  {:dim :number
   :integer true
   :value (+ (:value %1) (:value %2))
   :grain 1}
```

Is this currently supported in any way? Do I have to fall back to regexes? This comes up on multiple other occasions such as ordinals and date handling.

**Comment by Mikulas** [comment]
This seems to be similar issue: https://github.com/wit-ai/duckling/issues/91

In this case, falling back to regex is not an option. Each number can have roughly 20 inflections and the regex grows exponentially. Even if the regex was to be generated automatically, the performance would probably be terrible.

**Comment by patapizza** [comment]
Hi @Mikulas, sorry for the late response.
This is something not supported at the moment unfortunately. Would it make sense to write `tři a třicet` (with spaces)? I'm thinking that you can implement it with spaces until we figure out a good way to handle `třiatřicet`. Let me know if that works for you.

**Comment by Mikulas** [comment]
Thank you for for the update.
Unfortunately the version with spaces is no good. While it makes sense semantically, users will not write it as such (and no STT engine would generate it with spaces).

What I did in the meantime is this: https://github.com/Mikulas/duckling/blob/cs/resources/languages/cs/rules/numbers.clj#L188-L221
