### ISSUE TITLE
Would you be so kind and provide an internal architecture schema for the library ?

### ISSUE THREAD

**Issue by danielmihai** [wit-ai/duckling#233]
Hi, 

Do you have an internal architecture plan of Duckling ? ( I know the code is the 'schema', but I'd need something more visual)

Thank you very much! 

Best Regards,
Daniel.

**Comment by almostimplemented** [comment]
Be sure to read https://duckling.wit.ai/ and in particular the [implementation section](https://duckling.wit.ai/#date-and-time-implementation).

`core.clj` is the entry point (where `parse` is defined), `engine.clj` has the shared parsing logic, `time/prod.clj` has helper functions used in the `rules`, `time/pred.clj` defines the time predicates, `time/obj.clj` defines the binding to actual Joda datetimes.
