### ISSUE TITLE
Handling timezone

### ISSUE THREAD

**Issue by akki2825** [wit-ai/duckling#237]
Interpretation of today or tomorrow is based on sever timezone where duckling is running. This poses a problem when the user is in a different timezone. 

For example, 'today' is Mar 30th, 2017 in UTC. For a user in PST 'today' would mean Mar 29th, 2017. The output we get here is Mar 30th, whereas, the output should have been Mar 29th . How do we include user timezone in context? 

Documentation also suggests that this is one of the limitations of Duckling. 
Is there a way to put timezone in context during parsing such that it affects the extracted time value?

**Comment by patapizza** [comment]
Hey @akki2825 you can pass a custom context to `parse`: https://github.com/wit-ai/duckling/blob/master/src/duckling/core.clj#L373

The timezone limitation is when parsing things like "9pm UTC". Duckling will parse the full text, but won't actually make the time computation.
