### ISSUE TITLE
Possibility to add function into rules.

### ISSUE THREAD

**Issue by andriusk** [wit-ai/duckling#238]
Hi all,

I am trying to add lithuanian language, but I am completely noob in Clojure and it seems like it would be from another world for me. :D 

The problem is that in lithuanian language there are a lot of cases to say one word, but the root of the word is same, only ending is changing and endings, in most cases  are the same also. 
So I am tired to writing same regex:
`#"(?i)pirmadien(is|io|iui|i|į|y|yje)"`

I would like do something like this (example in JavaScript)

'  "named-day"
  matchCommonCombination("pirmadien", word)
  (day-of-week 1)'

And have function like this:

`function matchCommonCombination(wordRoot, word) {
     var endings = ["is", "io", "iui", "i", "į", "y", "yje"];
     for (var i = 0; i < endings.length; i++) {
        if (wordRoot + endings[i] == word) {
            return true;
        }
    }

   return false;
}`

Is it possible to do that? Or only possible solution is to write same regex?

Thanks,
Andrius

**Comment by patapizza** [comment]
Hi Andrius,

I don't see an immediate solution to this. There is a related pain in languages with accents (e.g. French), where the alternative without accent needs to be set everywhere.
So for now, please duplicate the regex where needed.

Also you probably want to add the alternative `yje` before `y`.

**Comment by justinas-vd** [comment]
I am not sure that regex'es like 

#"(?i)pirmadien(is|io|iui|i|į|y|yje)"

make sense. Typically, you want an accusative case, i.e., "pirmadienį" ("pirmadienis" means "Monday"). For instance, "susitikime trečią valandą pirmadienį“ ("Let's meet at 3 PM on Monday"). In fact, I can't think of an example, where you would want the locative case "pirmadienyje" (literally "in the Monday").

I would strongly suggest to start with the basics and then to expand regex'es if you find a compelling and grammatically correct case where basic regexes don't work.

**Comment by andriusk** [comment]
Agree with You, @justinas-vd , but this regex is just an example. The problem was not here.

Thanks for replies.
