### ISSUE TITLE
Adding seconds to time causes date to be treated as an interval

### ISSUE THREAD

**Issue by logiclabs** [wit-ai/duckling#72]
For instance: **June 25 01:00:00**

The duckling demo app resolves this to:

`From Saturday, 25 June 2016 at 1:00:00 -0700 (PDT) to Saturday, 25 June 2016 at 13:00:00 -0700 (PDT)`

The results tokens show the time has been parsed as: `<time-of-day> - <time-of-day> (interval)`

**Comment by l5t** [comment]
Thanks for reporting. Just fixed it

**Comment by l5t** [comment]
![image](https://cloud.githubusercontent.com/assets/6992759/13937125/c55ed4f6-ef7f-11e5-96df-4fb639897a68.png)
in prod
